# Generated by Django 6.0.5 on 2026-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='correct_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='learned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='target_streak',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
